### ISSUE TITLE
Support for Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by shabmk** [JuliaCI/julia-buildbot#102]
As suggested on https://github.com/JuliaLang/julia/issues/30314#issuecomment-445478625 I'm opening the issue here on the appropriate repository to request Julia prebuilt binaries for Alpine Linux.

System information:

- Alpine Linux x86_64
- Linux 4.14.86-0-vanilla
- Musl 1.1.20
- BusyBox 1.29.3

Julia 0.6 was known to build on Alpine Linux, but was removed because they couldn't get the tests to pass. Some of them failed.

If any other information is needed, please request and I will happily provide.
Merry Xmas.

**Comment by staticfloat** [comment]
Hello @shabmk I'm really sorry that it's taken so long for me to find this, in the future please feel free to ping me via `@staticfloat` if I don't respond.

I think it will be reasonable for us to provide an `x86_64` musl-linked version of Julia in the future.  I can't say exactly when this will be available, but it's not too much work, we just need to add an `alpine` configuration to [this `Makefile`](https://github.com/staticfloat/julia-docker/blob/master/buildworker/Makefile) to generate docker images to build a buildworker that runs on Alpine, then add its configuration into this repository.

**Comment by rana** [comment]
Looking forward to an alpine release. Will help with running docker images

**Comment by ararslan** [comment]
We've been producing official binaries for musl Linux for a few releases now, so I'm going to close this. :slightly_smiling_face:
