### ISSUE TITLE
Add docbuild test

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/julia-buildbot#115]
@staticfloat in addition to runtests, we should have a doctest worker. Indeed, like travis, we can also optimize and run only that worker when applicable:
```
FILES_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE -- || git ls-files)
# skip tests if only files within the "doc" dir have changed
if [ $(echo "$FILES_CHANGED" | grep -cv '^doc/') -gt 0 ]; then
    <schedule all test workers>
end
<schedule doc test worker>
```

**Comment by staticfloat** [comment]
This can be done by analyzing the `files` attribute of a `change` object, and running an extra test within the normal `separated_testing` build steps.

**Comment by staticfloat** [comment]
How do we run the doctests?

**Comment by staticfloat** [comment]
Looks like the answer is `make -C doc doctest=true`
