### ISSUE TITLE
Add buildbot for clangsa

### ISSUE THREAD

**Issue by Keno** [JuliaCI/julia-buildbot#118]
Ping @staticfloat 

Once https://github.com/JuliaLang/julia/pull/32090 is merged, clangsa will be clean on the julia codebase. To ensure it stays that way, we should have a CI worker that runs it. Since clangsa doesn't require julia to be bootstrapped (or even julia to be built), it probably makes sense to have a separate worker that runs in parallel with the package_ workers (OS doesn't really matter - linux x86_64 seems fine - eventually we may want to rerun with different target arches but that's just an argument to the analyzer). I.e. all the bot would have to do is run `make -C src analyzegc`. Separately, it might make sense to just have the same worker also run the llvmpasses tests (`make -C test/llvmpasses`), since those currently only run on travis and they similarly do not require a bootstrapped julia.

**Comment by vchuravy** [comment]
Some of the llvmpasses do require a bootstrap Julia, I have been adding some end to end codegen tests

**Comment by Keno** [comment]
Ok, whatever is simplest then. Getting clangsa up is important so it doesn't break, but we do already test llvmpasses so that can wait
