### ISSUE TITLE
Set mcpu instead of march on ARM

### ISSUE THREAD

**Issue by ianshmean** [JuliaCI/julia-buildbot#148]
As per https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu
> You must use -mcpu for Arm and -march for x86

It seems to make sense to switch the ARM buildbots to use `mcpu` instead of `march`

I'm preparing a PR but thought I'd create an issue to link to in a code comment

cc. @staticfloat

**Comment by staticfloat** [comment]
Closing this in favor of the ARM pull request where Yichao is dispensing wisdom: https://github.com/JuliaCI/julia-buildbot/pull/151
