### ISSUE TITLE
Upload tar.gz and zip for nightlies

### ISSUE THREAD

**Issue by musm** [JuliaCI/julia-buildbot#161]
When opening an issue, please ping @staticfloat 

He does not receive emails automatically when new issues are created.
Without this ping, your issue may slip through the cracks!
If no response is garnered within a week, feel free to ping again.

**Comment by musm** [comment]
something related to https://github.com/JuliaCI/julia-buildbot/blob/a69bdd10f2fb886c04743750ee942b9d79e3f86e/master/builder_utils.py#L147 needs to get updated? Although those look like the upload the complete folder which should contain the zips and tarballs. 



I thought `def render_upload_command(props_obj):` took care of that

**Comment by staticfloat** [comment]
We now have `.tar.gz` files for all nightles.  Just change the typical `.dmg` or `.exe` extension to `.tar.gz`.  We also have `.zip` for Windows.

**Comment by musm** [comment]
I don't think this is fixed:
https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.zip
https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.tar.gz

Are not available.

**Comment by staticfloat** [comment]
Let's see if https://github.com/JuliaCI/julia-buildbot/pull/175 properly promotes these other archive types
