### ISSUE TITLE
Build and host a nightly full source tarball

### ISSUE THREAD

**Issue by Sacha0** [JuliaCI/julia-buildbot#169]
(Migrated from https://github.com/staticfloat/julia-nightly-packaging/issues/10.)

`@nhdaly`:
> Hi! 👋
> 
> In addition to the nightly binaries that are already built and hosted at https://julialang.org/downloads/nightlies/, is there any way we could start also building and hosting a nightly tar ball?
> 
> We (at RelationalAI) want to start building our product against the nightly builds so that we aren't stuck so far behind by regressions in a release again like we've been with julia 1.5.
> 
> But our build farm, which is built on nix, does everything via source builds. It would be amazingly helpful if we could have it pull a nightly tar ball to build julia from! Is that something that would be easy to do?
> 
> Thanks so much in advance for your consideration! :)
> Best,
> ~Nathan
> 

`@rbvermaa`:
> Note that our build needs the *-full tarballs, so it would be greatly appreciated if this can be published somewhere next to the binary builds.

**Comment by staticfloat** [comment]
WIP PR here: https://github.com/JuliaCI/julia-buildbot/pull/170

**Comment by staticfloat** [comment]
Note quite working yet; `full-source-dist` has bitrotted a bit, fix pending here: https://github.com/JuliaLang/julia/pull/38047

**Comment by Sacha0** [comment]
Now working thanks to Elliot! 🙏
