### ISSUE TITLE
Upload coverage reports even if some CI checks fail

### ISSUE THREAD

**Issue by bramtayl** [JuliaCI/julia-buildbot#173]
I tried to make a PR, but I can't figure it out. Ref https://github.com/JuliaLang/julia/issues/34643

**Comment by vtjnash** [comment]
I think you might be confused. We don't run the coverage pass on PRs (https://github.com/JuliaCI/julia-buildbot/blob/master/master/coverage.py)

**Comment by bramtayl** [comment]
Well, I'm very likely confused, but I'm not talking about coverage reports from PR, but coverage reports from commits. It looks like the last time coverage was uploaded from master was 07 Oct 2020 02:42AM UTC if I'm reading it correctly?

**Comment by vtjnash** [comment]
Ah, you're on the wrong repo for that. You want https://github.com/JuliaCI/CoverageBase.jl/issues/42

**Comment by bramtayl** [comment]
Ok, thanks!
