### ISSUE TITLE
Nightly Windows Binaries are not signed

### ISSUE THREAD

**Issue by musm** [JuliaCI/julia-buildbot#181]
@staticfloat 

Is there any reason we skip signing for the nightly executables? It ends up getting flagged by Windows when trying to download them.

**Comment by staticfloat** [comment]
they should be getting signed.  Here's an example build that looks like it was signed properly: https://build.julialang.org/#/builders/21/builds/7923

**Comment by musm** [comment]
You are right they are signed, I don't know why Windows flag the downloads from https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe

**Comment by musm** [comment]
For example when I download the release versions don't have the same issue.

**Comment by staticfloat** [comment]
I believe that’s because windows antivirus has a threshold of the number of
times an executable needs to be seen in the wild before it is accepted as
“safe” or some such.

**Comment by musm** [comment]
I see, I guess we can't control that.
