### ISSUE TITLE
Update timestamp server

### ISSUE THREAD

**Issue by musm** [JuliaCI/julia-buildbot#200]
https://stackoverflow.com/questions/9714798/http-timestamp-verisign-com-scripts-timstamp-dll-not-available

> http://timestamp.verisign.com/scripts/timstamp.dll has limped along for the last few years and had been working in a sort of depreciated state, but the new owners of the certificate issuing business, DigiCert, have issued a migration alert.

Server should be updated to: http://timestamp.verisign.com/scripts/timstamp.dll -> http://timestamp.digicert.com/?alg=sha1

**Comment by vtjnash** [comment]
This seems to have propelled itself from necessary to urgent, as all buildbots are now failing on this step

**Comment by staticfloat** [comment]
Done
