### ISSUE TITLE
When constructing the `OldBuildCanceller`, construct the list of builder names programmatically

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildbot#254]
Currently, when constructing the `OldBuildCanceller`, we manually specify the list of builder names. However, we should instead construct this list of builder names programmatically.

https://github.com/JuliaCI/julia-buildbot/blob/05e1b20bc022f8143875a076a55d0949dd4f5414/master/inventory.py#L228-L258

**Comment by DilumAluthge** [comment]
Note: if I understand correctly, `all_names` is not the correct thing to pass here. As far as I can tell, `all_names` is a list of _worker_ names. In contrast, I think that `OldBuildCanceller` expects a list of _builder_ names.

**Comment by DilumAluthge** [comment]
@staticfloat Any ideas on how we might be able to construct the `builders_to_auto_cancel` list programmatically?

**Comment by staticfloat** [comment]
I'm okay with just keeping it hardcoded for now; I don't want to spend more brainpower maintaining buildbot than is absolutely necessary.

**Comment by DilumAluthge** [comment]
Let's just keep this hardcoded indefinitely until we move to Buildkite.

For Buildkite, the "auto cancel" feature is very easy to use and is managed entirely from the web interface.
