### ISSUE TITLE
LLVM patches sometimes get ignored 

### ISSUE THREAD

**Issue by vchuravy** [JuliaCI/julia-buildbot#71]
As noted on https://build.julialang.org/#/builders/22/builds/537 and previously with patches for LLVM.jl.
LLVM patches sometimes are ignored on the the buildbots, this might actually be a issue with the Makefiles (cc: @vtjnash) 
I had this locally where adding a patch didn't trigger a LLVM rebuild.

In any case since we are now using `CCACHE` we might want to consider building from scratch on the buildbots 

cc: @staticfloat

**Comment by staticfloat** [comment]
https://github.com/JuliaCI/julia-buildbot/pull/72

**Comment by staticfloat** [comment]
Okay done.  Let's see how well this works.
